version: '3.6'

services:
  question-task:
    build: .
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://test:test@db:5432/test
    networks:
      - default
    ports:
      - 5050:5000
#    volumes:
#      - ./app:/usr/src/app/app
    restart: always

  db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    image: postgres:latest
    networks:
      - default
    ports:
      - 5555:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data