version: '3.6'

services:
  db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    image: postgres:latest
    networks:
      - default
    ports:
      - 5555:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


  question-task:
    build: .
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://test:test@db:5432/test
    networks:
      - default
    ports:
      - 5050:5000
    volumes:
      - ./app:/usr/src/app/app
      - ./migrations:/usr/src/app/migrations
    restart: always
    command: gunicorn -w 1 -b 0.0.0.0:5000 app:app